"""
ML configuration - single source of truth for training and inference settings.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field

# ponytail: full S&P 500 list collapsed into a helper so dev runs use a fast
# subset (~55 tickers = ~19s/epoch on MPS) and prod runs can opt-in to all 475
# via TRAINING_TICKERS env var. Re-expanding the inline list would be the same
# data — kept here as a single source of truth.
_ALL_SP500 = [
    "A",
    "AAL",
    "AAPL",
    "ABBV",
    "ABC",
    "ABT",
    "ACN",
    "ADBE",
    "ADI",
    "ADM",
    "ADP",
    "ADSK",
    "AEP",
    "AES",
    "AFL",
    "AIG",
    "AIZ",
    "AJG",
    "AKAM",
    "ALB",
    "ALGN",
    "ALL",
    "ALLE",
    "AMAT",
    "AMD",
    "AMGN",
    "AMP",
    "AMT",
    "AMZN",
    "ANET",
    "ANSS",
    "AON",
    "AOS",
    "APA",
    "APD",
    "APH",
    "ARE",
    "ATO",
    "AVB",
    "AVGO",
    "AVY",
    "AWK",
    "AXP",
    "AZO",
    "BA",
    "BAC",
    "BAX",
    "BBWI",
    "BBY",
    "BDX",
    "BEN",
    "BF.B",
    "BG",
    "BIIB",
    "BK",
    "BKNG",
    "BKR",
    "BLK",
    "BLL",
    "BMY",
    "BR",
    "BRK.B",
    "BRO",
    "BSX",
    "BWA",
    "BXP",
    "C",
    "CAG",
    "CAH",
    "CARR",
    "CAT",
    "CB",
    "CBOE",
    "CBRE",
    "CDNS",
    "CDW",
    "CE",
    "CEG",
    "CF",
    "CFG",
    "CHD",
    "CHRW",
    "CHTR",
    "CI",
    "CINF",
    "CL",
    "CLX",
    "CMA",
    "CMCSA",
    "CME",
    "CMG",
    "CMI",
    "CMS",
    "CNC",
    "CNP",
    "COF",
    "COO",
    "COP",
    "COST",
    "CPB",
    "CPRT",
    "CRM",
    "CRL",
    "CRWD",
    "CSCO",
    "CSGP",
    "CSX",
    "CTAS",
    "CTLT",
    "CTRA",
    "CTSH",
    "CTVA",
    "CVS",
    "CVX",
    "D",
    "DAL",
    "DD",
    "DE",
    "DECK",
    "DFS",
    "DG",
    "DGX",
    "DHI",
    "DHR",
    "DIS",
    "DLR",
    "DLTR",
    "DOV",
    "DPZ",
    "DRI",
    "DTE",
    "DUK",
    "DVN",
    "DXC",
    "DXCM",
    "EA",
    "EBAY",
    "ECL",
    "ED",
    "EFX",
    "EG",
    "EIX",
    "EL",
    "ELV",
    "EMN",
    "EMR",
    "ENPH",
    "EOG",
    "EQIX",
    "EQR",
    "EQT",
    "ES",
    "ESS",
    "ETN",
    "ETR",
    "ETSY",
    "EVRG",
    "EW",
    "EXC",
    "EXPD",
    "EXPE",
    "EXR",
    "F",
    "FANG",
    "FAST",
    "FCX",
    "FDX",
    "FE",
    "FFIV",
    "FI",
    "FIS",
    "FISV",
    "FITB",
    "FLR",
    "FLS",
    "FMC",
    "FOX",
    "FOXA",
    "FRT",
    "FSLR",
    "FTNT",
    "FTV",
    "GD",
    "GE",
    "GEHC",
    "GEN",
    "GILD",
    "GIS",
    "GL",
    "GLW",
    "GM",
    "GNRC",
    "GOOG",
    "GOOGL",
    "GPC",
    "GPN",
    "GRMN",
    "GS",
    "GWW",
    "HAL",
    "HAS",
    "HBAN",
    "HCA",
    "HD",
    "HES",
    "HIG",
    "HII",
    "HLT",
    "HOLX",
    "HON",
    "HPE",
    "HPQ",
    "HRL",
    "HSIC",
    "HST",
    "HSY",
    "HUM",
    "HWM",
    "IBM",
    "ICE",
    "IDXX",
    "IEX",
    "IFF",
    "ILMN",
    "INCY",
    "INTC",
    "INTU",
    "INVH",
    "IP",
    "IPG",
    "IQV",
    "IR",
    "IRM",
    "ISRG",
    "IT",
    "ITW",
    "IVZ",
    "J",
    "JBHT",
    "JCI",
    "JKHY",
    "JNJ",
    "JNPR",
    "JPM",
    "K",
    "KDP",
    "KEY",
    "KEYS",
    "KHC",
    "KIM",
    "KLAC",
    "KMB",
    "KMI",
    "KMX",
    "KO",
    "KR",
    "KVUE",
    "L",
    "LDOS",
    "LEN",
    "LH",
    "LHX",
    "LIN",
    "LKQ",
    "LLY",
    "LMT",
    "LNC",
    "LNT",
    "LOW",
    "LRCX",
    "LULU",
    "LUV",
    "LW",
    "LYB",
    "LYV",
    "MA",
    "MAA",
    "MAR",
    "MAS",
    "MCD",
    "MCHP",
    "MCK",
    "MDLZ",
    "MDT",
    "MET",
    "MGM",
    "MHK",
    "MKC",
    "MKTX",
    "MLM",
    "MMC",
    "MMM",
    "MNST",
    "MO",
    "MOH",
    "MOS",
    "MPC",
    "MPWR",
    "MRK",
    "MRNA",
    "MRO",
    "MS",
    "MSCI",
    "MSFT",
    "MSI",
    "MTB",
    "MTD",
    "MU",
    "NCLH",
    "NDAQ",
    "NDSN",
    "NEE",
    "NEM",
    "NFLX",
    "NI",
    "NKE",
    "NOC",
    "NOW",
    "NRG",
    "NSC",
    "NTAP",
    "NTRS",
    "NUE",
    "NVDA",
    "NVR",
    "NWS",
    "NWSA",
    "NXPI",
    "O",
    "ODFL",
    "OKE",
    "OMC",
    "ON",
    "ORCL",
    "ORLY",
    "OTIS",
    "OXY",
    "PANW",
    "PARA",
    "PAYC",
    "PAYX",
    "PCAR",
    "PCG",
    "PEAK",
    "PEP",
    "PFE",
    "PFG",
    "PG",
    "PGR",
    "PH",
    "PHM",
    "PKG",
    "PLD",
    "PM",
    "PNC",
    "PNR",
    "PNW",
    "PODD",
    "PPG",
    "PPL",
    "PRU",
    "PSA",
    "PSX",
    "PVH",
    "PWR",
    "PXD",
    "PYPL",
    "QCOM",
    "QRVO",
    "RCL",
    "REG",
    "REGN",
    "RF",
    "RHI",
    "RJF",
    "RL",
    "RMD",
    "ROK",
    "ROL",
    "ROP",
    "ROST",
    "RSG",
    "RTX",
    "SBAC",
    "SBUX",
    "SCHW",
    "SEE",
    "SHW",
    "SJM",
    "SLB",
    "SMCI",
    "SNPS",
    "SO",
    "SPG",
    "SPGI",
    "SRE",
    "STE",
    "STLD",
    "STT",
    "STX",
    "STZ",
    "SWK",
    "SWKS",
    "SYF",
    "SYK",
    "SYY",
    "T",
    "TAP",
    "TDG",
    "TDY",
    "TECH",
    "TEL",
    "TER",
    "TFC",
    "TFX",
    "TGT",
    "TJX",
    "TMO",
    "TMUS",
    "TPR",
    "TRGP",
    "TRMB",
    "TROW",
    "TRV",
    "TSCO",
    "TSLA",
    "TSN",
    "TT",
    "TTWO",
    "TXN",
    "TXT",
    "TYL",
    "UDR",
    "UHS",
    "ULTA",
    "UNH",
    "UNP",
    "UPS",
    "URI",
    "USB",
    "V",
    "VFC",
    "VICI",
    "VLO",
    "VMC",
    "VRSK",
    "VRSN",
    "VRTX",
    "VTR",
    "VTRS",
    "VZ",
    "WAB",
    "WAT",
    "WBA",
    "WBD",
    "WDC",
    "WEC",
    "WELL",
    "WFC",
    "WM",
    "WMB",
    "WMT",
    "WRB",
    "WRK",
    "WST",
    "WY",
    "WYNN",
    "XEL",
    "XOM",
    "XRAY",
    "XYL",
    "YUM",
    "ZBH",
    "ZBRA",
    "ZTS",
]

_DEV_SUBSET = _ALL_SP500[:55]  # ~19s/epoch on MPS — fast iteration


def _train_tickers_env() -> list[str]:
    """Return ticker list: TRAINING_TICKERS env (comma-sep) or dev subset."""
    env = os.environ.get("TRAINING_TICKERS")
    if env:
        return [t.strip() for t in env.split(",") if t.strip()]
    return _DEV_SUBSET


@dataclass(frozen=True)
class MLConfig:
    """All ML training and inference configuration."""

    # Sequence settings
    SEQUENCE_LENGTH: int = 30
    N_FEATURES: int = 17  # 13 V1 + vol_pct + 3 cross-sectional (excess_ret_1d/5d/21d vs SPY)
    BENCHMARK_TICKER: str = "SPY"  # Market benchmark for cross-sectional features

    # Labeling — widened threshold from 0.3→0.7 so FLAT band is ±1.57σ₃₀*√5,
    # giving ~52% FLAT. Directional labels now reflect stronger (>2σ₅) moves
    # with higher signal-to-noise ratio instead of labeling noise as directional.
    VOL_LOOKBACK: int = 30
    THRESHOLD_MULT: float = 0.7  # σ multiplier for FLAT band. 0.3 gave ~28% FLAT — UP/DOWN
    # labels were indistinguishable from noise.
    FORECAST_HORIZON: int = 5  # N-day forward return (1=daily, 5=weekly, 21=monthly)

    # Volatility regime filter — only train on windows where the ticker's 30-day
    # rolling vol is above this percentile of its own history. Low-vol periods
    # produce labels that are mostly noise (tiny moves classified as directional).
    # 0.40 = keep top 60% of vol regimes per ticker.
    VOL_FILTER_PERCENTILE: float = 0.40

    # Model architecture — V1 LSTM only. V2 (Conv1D+BiLSTM+Attention+RegimeGate)
    # tested and caused gradient stall — 203k params could never escape uniform init.
    EMBED_DIM: int = 16
    HIDDEN_DIM: int = 64  # reduced from 128 to reduce overfitting to noise
    N_LAYERS: int = 2  # 1 layer collapsed to majority-class prediction
    DROPOUT: float = 0.5  # increased from 0.3/0.4 for noisy financial data
    N_CLASSES: int = 3  # DOWN, FLAT, UP

    # Training
    EPOCHS: int = 100
    BATCH_SIZE: int = 256  # 256 for MPS GPU memory efficiency
    LEARNING_RATE: float = 1e-3
    WEIGHT_DECAY: float = (
        1e-3  # increased from 1e-5 to suppress overfitting on noisy financial data
    )
    PATIENCE: int = 15  # number of epochs without directional accuracy improvement before stopping
    MIN_DELTA: float = 5e-3  # minimum directional accuracy improvement to reset patience (0.5%)
    FOCAL_GAMMA: float = (
        2.0  # focal loss focusing parameter — down-weights well-classified FLAT samples
    )

    # Split
    TRAIN_SPLIT: float = 0.7
    VAL_SPLIT: float = 0.15
    TEST_SPLIT: float = 0.15

    # Data
    TRAINING_TICKERS: list[str] = field(default_factory=lambda: _train_tickers_env())
    OHLCV_YEARS: int = 6  # Training window — was 20yr, reduced to 6yr for ~9s/epoch epochs

    # Paths
    MODEL_ARTIFACT_DIR: str = field(
        default_factory=lambda: os.environ.get("MODEL_ARTIFACT_DIR", "/model_artifacts/champion")
    )
    MLFLOW_TRACKING_URI: str = field(
        default_factory=lambda: os.environ.get("MLFLOW_TRACKING_URI", "http://mlflow:5000")
    )
    DATABASE_URL: str = field(
        default_factory=lambda: os.environ.get(
            "DATABASE_URL", "postgresql+asyncpg://stocklens:stocklens@postgres:5432/stocklens"
        )
    )

    @property
    def SYNC_DATABASE_URL(self) -> str:
        """Return a sync psycopg2-compatible DSN for pandas.read_sql.

        Strips the ``+asyncpg`` suffix from the async DSN.
        """
        return self.DATABASE_URL.replace("postgresql+asyncpg://", "postgresql://", 1)

    # Inference
    MIN_OHLCV_DAYS: int = 60  # Minimum days needed for feature computation (30 window + padding)
    PREDICTION_CACHE_TTL: int = 21600  # 6 hours in seconds

    # Class names
    CLASS_NAMES: tuple[str, ...] = ("DOWN", "FLAT", "UP")


ML_CONFIG = MLConfig()
