"""d2f4e1b3c5a7 — identity bridge

This revision reconciles the initial migration file rename.

The very first migration was auto-generated by Alembic with revision
``d2f4e1b3c5a7``.  Before the first commit the file was manually renamed
to ``0001_initial_schema.py`` and the ``revision`` field was changed to
``0001``.  However the dev database had already been stamped with the
auto-generated hash, so every deployment that runs ``alembic upgrade head``
from an existing database hits::

    Can't locate revision identified by 'd2f4e1b3c5a7'

This revision restores ``d2f4e1b3c5a7`` as a real file in the Alembic
version DAG so the chain becomes::

    d2f4e1b3c5a7 (no-op) → 0001 → 0002 → … → 0010

The ``upgrade()`` is empty because the schema was applied by the original
(un-renamed) run.  On a **fresh** database Alembic applies this no-op
first, then walks the rest of the chain as usual.

Revision ID: d2f4e1b3c5a7
Revises:
Create Date: 2026-07-18
"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "d2f4e1b3c5a7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """No-op — schema already applied by the original run."""
    pass


def downgrade() -> None:
    """No-op — the original run has nothing to undo."""
    pass
